### ISSUE TITLE
I thought "+" would let me post something new with that tag

### ISSUE THREAD

**Issue by rissole** [jjcm/soci#61]
![image](https://user-images.githubusercontent.com/2404098/113469050-32031480-9496-11eb-896f-d4e3418bde07.png)

**Comment by jjcm** [comment]
Oh very interesting - this makes a lot of sense. I'll switch this out to a star icon.

**Comment by jjcm** [comment]
Closing because the reporter can't make up their mind: 

![image](https://user-images.githubusercontent.com/50971/124522345-c76cb800-dda7-11eb-9bf4-14eee8b071d3.png)

**Comment by jjcm** [comment]
![image](https://user-images.githubusercontent.com/50971/124522387-f1be7580-dda7-11eb-8bb5-1d8dd5b0a80f.png)
Options tried for future ref
