### ISSUE TITLE
Always get "A title is required" when posting content

### ISSUE THREAD

**Issue by rissole** [jjcm/soci#62]
![image](https://user-images.githubusercontent.com/2404098/113469152-151b1100-9497-11eb-8cf3-cfca4a7bc0b3.png)

tried refreshing, plaintext... can never post without this error

**Comment by jjcm** [comment]
Fixed in https://github.com/jjcm/soci-frontend/commit/85a0fc7db7e53b9518c8af5971dadbf4e158ff67
