### ISSUE TITLE
Login button remains in loading state on error 

### ISSUE THREAD

**Issue by rissole** [jjcm/soci#72]
![image](https://user-images.githubusercontent.com/2404098/115144202-b5278b80-a08e-11eb-8ecb-2a768d36058b.png)

I get error "email must contain @" then button never leaves loading state

**Comment by jjcm** [comment]
Fixed in https://github.com/jjcm/soci-frontend/commit/5e05d2b10e46bfcd674e26431bf9baf74d975b88
