### ISSUE TITLE
new, unedited comments on posts appear with 'edited' label 

### ISSUE THREAD

**Issue by rissole** [jjcm/soci#77]
![image](https://user-images.githubusercontent.com/2404098/115144542-87dbdd00-a090-11eb-9037-9cbbdf67af3a.png)

**Comment by jjcm** [comment]
100% a bug. TY.

**Comment by jjcm** [comment]
Fixed in https://github.com/jjcm/soci-frontend/commit/33d9747941a2a0a77a0e30bad8b8fd4ef8b50f76
