### ISSUE TITLE
when uploading a video, i get "uploading undefined" in the loading state

### ISSUE THREAD

**Issue by rissole** [jjcm/soci#80]
it was uploading this vid: https://non.io/japanesetitle

**Comment by jjcm** [comment]
Got a screenshot of this? Was it via dragging a video in, or via selecting a vid via the file dialog?

**Comment by jjcm** [comment]
Fixed in https://github.com/jjcm/soci-frontend/commit/91420d074a1cb896efd6a212e4c6ba6f5d2b4ff9
