### ISSUE TITLE
Time on posts is displayed as "1 months ago"

### ISSUE THREAD

**Issue by karchbold** [jjcm/soci#89]
![image](https://user-images.githubusercontent.com/49083233/116836652-b0c0ae00-ac0a-11eb-8389-fcc4f4fd36e5.png)

**Comment by jjcm** [comment]
Fixed in https://github.com/jjcm/soci-frontend/commit/9fc1765d782ecdae9ee4632a67e38d5a4db89ca5
ty @karchbold for the report  <3
